export const OrderData = [
  {
    orderId: "#5010",
    menu: "Key Tags",
    amount: 750,
    processingStatus: "Processing",
    pendingStatus: "Pending",
    cancelledStatus: "Cancelled",
    completedStatus: "Completed",
  },
  {
    orderId: "#1041",
    menu: "Protein bars",
    amount: 352,
    processingStatus: "Processing",
    pendingStatus: "Pending",
    cancelledStatus: "Cancelled",
    completedStatus: "Completed",
  },
  {
    orderId: "#1425",
    menu: "protein shakes",
    amount: 120,
    processingStatus: "Processing",
    pendingStatus: "Pending",
    cancelledStatus: "Cancelled",
    completedStatus: "Completed",
  },
  {
    orderId: "#5242",
    menu: "Protein powder",
    amount: 425,
    processingStatus: "Processing",
    pendingStatus: "Pending",
    cancelledStatus: "Cancelled",
    completedStatus: "Completed",
  },
  {
    orderId: "#5563",
    menu: "supplements",
    amount: 125,
    processingStatus: "Processing",
    pendingStatus: "Pending",
    cancelledStatus: "Cancelled",
    completedStatus: "Completed",
  },
];
