export const OrderData = [
  {
    orderId: "#5010",
    menu: "Key Tags",
    amount: 145,
    processingStatus: "Processing",
    pendingStatus: "Pending",
    cancelledStatus: "Cancelled",
    completedStatus: "Completed",
  },
  {
    orderId: "#5010",
    menu: "Key Tags",
    amount: 145,
    processingStatus: "Processing",
    pendingStatus: "Pending",
    cancelledStatus: "Cancelled",
    completedStatus: "Completed",
  },
  {
    orderId: "#5010",
    menu: "Key Tags",
    amount: 145,
    processingStatus: "Processing",
    pendingStatus: "Pending",
    cancelledStatus: "Cancelled",
    completedStatus: "Completed",
  },
  {
    orderId: "#5010",
    menu: "Key Tags",
    amount: 145,
    processingStatus: "Processing",
    pendingStatus: "Pending",
    cancelledStatus: "Cancelled",
    completedStatus: "Completed",
  },
  {
    orderId: "#5010",
    menu: "Key Tags",
    amount: 145,
    processingStatus: "Processing",
    pendingStatus: "Pending",
    cancelledStatus: "Cancelled",
    completedStatus: "Completed",
  },
  {
    orderId: "#5010",
    menu: "Key Tags",
    amount: 145,
    processingStatus: "Processing",
    pendingStatus: "Pending",
    cancelledStatus: "Cancelled",
    completedStatus: "Completed",
  },
  {
    orderId: "#5010",
    menu: "Key Tags",
    amount: 145,
    processingStatus: "Processing",
    pendingStatus: "Pending",
    cancelledStatus: "Cancelled",
    completedStatus: "Completed",
  },
];
