import {
  FaUsersCog,
  FaArrowCircleUp,
  FaUserGraduate,
  FaDumbbell,
  FaFileAlt,
  FaBoxes,
  FaWalking,
} from "react-icons/fa";

export const OverviewData = [
  {
    id: 1,
    Icon: <FaUsersCog />,
    counter: "+2 (D)",
    upArrow: <FaArrowCircleUp />,
    total: 10,
    secType: "Total Employee",
  },
  {
    id: 2,
    Icon: <FaUserGraduate />,
    counter: "+18 (D)",
    upArrow: <FaArrowCircleUp />,
    total: 570,
    secType: "Total Students",
  },
  {
    id: 3,
    Icon: <FaDumbbell />,
    counter: "-2 (D)",
    upArrow: <FaArrowCircleUp />,
    total: 125,
    secType: "Total Equipments",
  },
  {
    id: 4,
    Icon: <FaFileAlt />,
    counter: "+2 (D)",
    upArrow: <FaArrowCircleUp />,
    total: 8,
    secType: "Total Applications",
  },
  {
    id: 5,
    Icon: <FaBoxes />,
    counter: "+18 (D)",
    upArrow: <FaArrowCircleUp />,
    total: 375,
    secType: "Total Products",
  },
  {
    id: 6,
    Icon: <FaWalking />,
    counter: "+16 (D)",
    upArrow: <FaArrowCircleUp />,
    total: 94,
    secType: "Total Exercise",
  },
];
